### ISSUE TITLE
PG12 Support and 2.0GA

### ISSUE THREAD

**Issue by luss** [HypoPG/hypopg#45]
any plans

**Comment by rjuju** [comment]
Hi,

postgres 12 (and 13) are already fully supported on the REL1_STABLE branch.

There's unfortunately still no clear date for 2.0 GA as the pg12 compatibility for hypothetical partitioning is quite complex.

**Comment by anthonator** [comment]
Should hypopg be used in production with pg12?

**Comment by rjuju** [comment]
Hi @anthonator, yes hypopg can be saefly used in production with pg12 using the last stable version (1.1.3).

Please note that hypothetical BRIN indexes won't work until postgres 12.2 is released, as a required fix has just been pushed (see https://github.com/postgres/postgres/commit/168d2064001f704965899bb2057591271c44e57a).

**Comment by anthonator** [comment]
Just a heads up. Postgres 12.2 has been released.

**Comment by rjuju** [comment]
Thanks for the heads up!

Since the issue with BRIN indexes was in postgres, not hypopg, no changes needed to be done in hypopg.  However, if anyone is using an older minor version of postgres but is still updating hypopg, I added specific error messages when trying to create a hypothetical BRIN index with the minimal minor version required, instead of failing with a cryptic error message later when the hypothetical index is use.

For the 2.0 version and hypothetical partitioning, unfortunately we're not there yet, as the partitioning code changed *a lot* between pg10 and pg11, and then *a lot again* between pg11 and pg12, and finding workarounds for the various things that needs to be done has to be adapted for each.
