### ISSUE TITLE
inaccurate cost estimation from explain

### ISSUE THREAD

**Issue by sylph520** [HypoPG/hypopg#48]
Very promising project. I'm new here, when I tried out the extension, I found a problem described below
environment: debiain 10, postgres 10
1. example table hypo like in the README
2. created a real index on id, and a real index real_index(id)
![image](https://user-images.githubusercontent.com/4487630/78142705-d9063800-745f-11ea-9254-6eb504c0dbd2.png)
3. now whether I drop or not drop the real index, the cost estimation results is like below
![image](https://user-images.githubusercontent.com/4487630/78142866-0c48c700-7460-11ea-9454-381764c5e063.png)
------->>>>>> the problem is the cost evaluation value don't equal?
I don't know whether it's bug or something else, plz check it out, thanks!

**Comment by rjuju** [comment]
Hello,

Thanks!

That behavior is quite expected.  The best hypopg can do is estimate with hopefully close enough results what a real index looks like (as in number of rows and size), but there'll always be a delta.

First hypopg use the existing statistics to do the estimation, so if the statistics are a little bit off, so will be hypopg estimates.  Then, hypopg tries to simulate an index in a more or less average state, so trying to account for bloat that happens on a index as soon as some write activity happens on the underlying table.  In your case the index is new so there shouldn't be any bloat on it.  Note that even with the simulated bloat, the hypothetical index is still slightly cheaper than your real index,.but all in all, the results are quite close and that what's important  here to to know how postgres would behave if the index did exist.

**Comment by sylph520** [comment]
I see, thanks for the reply!  an additional question, Since I didn't look into the internal mechanism of  postgres cost estimation involving actual index scan, I wonder is this process of postgres very complicated? (p.s. I looked the document of postgres but only to find a example of cost computation about table seq scan using formulas),

**Comment by rjuju** [comment]
Cost for indexes uses globally the same basis as sequential scan (random_page_cost instead of seq_page_cost, but the other cost parameters are used similarly), but the various heuristic to estimate the number of index pages and tuples touched are way more complex, and also depends on each index access method, so that's why it's much harder to come up with a clear explanation for index scan.

For instance, you can check how that costing is done for btree indexes looking at btcostestimate function (https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/selfuncs.c#L6042), which also depends on genericcostestimate (https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/selfuncs.c#L5803)

**Comment by sylph520** [comment]
I will check the references you provide. Thanks again!
