### ISSUE TITLE
hypo index is not working on partition table

### ISSUE THREAD

**Issue by nagaraju11** [HypoPG/hypopg#52]
I have created a hypo index on the partition table column, but when I run, `explain` query it doing `seq scan` instead `hypo index scan`.

Is it a bug or expected behavior?

`select version();` -->  PostgreSQL 10.11, compiled by Visual C++ build 1800, 64-bit

**Comment by rjuju** [comment]
Hello,

Did you create the hypothetical index on the root partitioned table or on the partition itself?  For now it should work if you create the hypothetical index on the partition.

I'll work on a patch to make any hypothetical index created on a root partitioned table automatically work for partitions, but not that this won't be effective for postgres 10, as this version has the exact same behavior (it changed with postgres 11 if I recall correctly).

**Comment by nagaraju11** [comment]
Yes, I have created on the partitioned tables directly.

**Comment by rjuju** [comment]
So I pushed a fix to prevent adding hypthetical indexes on partitioned tables for pg10 (and otherwise other non supported object), see https://github.com/HypoPG/hypopg/commit/098c8069f1ee1cdb2bd38669641b12f9ef04f30d.

Creating index on partitioned table is only supported since pg11, so I made it the same way for hypothetical indexes, see https://github.com/HypoPG/hypopg/commit/205482a733c98e1ad4759bcbd34d4d464d2b77c8.

Thanks a lot for the report!
