### ISSUE TITLE
Error when creating extension

### ISSUE THREAD

**Issue by nikhil-postgres** [HypoPG/hypopg#57]
Hi,

I am getting below error when creating the extension:

-bash-4.2$ psql
psql (11.11)
Type "help" for help.

postgres=# create extension hypopg;
ERROR:  could not load library "/usr/pgsql-11/lib/hypopg.so": /usr/pgsql-11/lib/hypopg.so: undefined symbol: pg_leftmost_one_pos32

When I did "sudo make install", I had got one warning related to pg_leftmost_one_pos32

hypopg_index.c:1954:2: warning: implicit declaration of function ‘pg_leftmost_one_pos32’ [-Wimplicit-function-declaration]
  num_bitmap = Max(1, num_overflow /
  ^
hypopg_index.c:1955:7: warning: implicit declaration of function 'pg_leftmost_one_pos32' is invalid in C99 [-Wimplicit-function-declaration]
                                         pg_leftmost_one_pos32(HypoHashGetMaxBitmapSize()));

**Comment by nikhil-postgres** [comment]
I used yum to install hypopg and It is working for me now.

**Comment by rjuju** [comment]
Hello @nikhil-postgres 

For the record it's due to some work in progress to add support for hypothetical hash indexes.  I didn't check the compatibility with older branches yet, thus this error.  If you use the lastest released tag it should compile without any problem.  But in any case using packages is the best way to install hypopg and other extensions!

**Comment by rjuju** [comment]
FYI: I just pushed a fix at https://github.com/HypoPG/hypopg/commit/a4acac04d125cae2eb8f2358dd196dbe029a813e.

Thanks a lot for the report!
