### ISSUE TITLE
Can't create hypopg extension on ubuntu?

### ISSUE THREAD

**Issue by anubhabmondalDirac** [HypoPG/hypopg#60]
first I install 'make'
but then if try to create extension i get this error
![hypopg](https://user-images.githubusercontent.com/69718132/134630629-ccf89548-3339-4977-93ef-ff998257febc.png)
@pepl @joelvh @rdunklau @rjuju Can you please help me on this?

**Comment by rjuju** [comment]
Hi.  First no need to ping 4 persons, creating an issue is enough.

About your problem, it seems that hypopg isn't installed.  If you tried to install it from source, then you're missing the `make install` step.  But since you're on ubuntu 20.04, there are official packages from the PGDG available.  See https://wiki.postgresql.org/wiki/Apt for instructions on how to proceeed.

I realize that I didn't update the documentation to mention it, so I'll fix that shortly.

**Comment by anubhabmondalDirac** [comment]
I just run this command it work fine --
# apt install postgresql-server-dev-12 (Example for PostgreSQL 11)
# apt install postgresql-12-hypopg
@rjuju Thanks
