### ISSUE TITLE
document how to enable hypo_use_real_oids

### ISSUE THREAD

**Issue by piracio** [HypoPG/hypopg#65]
Hi, I am trying to find how to enable the variable hypo_use_real_oids, the documentation mention this variable however it is unclear how to enable it.

**Comment by e-Evolution** [comment]
Hi @rjuju , we tried HyPopg from 1.3.1 version and PG 14.4  , and MacOS aarm and I got this error:

context : we are executed dexter with HyPopg


Processing 31 new query fingerprints
Index found: adempiere.ad_column (iskey)
Processing 165 new query fingerprints
ERROR: PG::InternalError: ERROR:  hypopg: not more oid available
HINT:  Remove hypothetical indexes or enable hypopg.use_real_oids

![image](https://user-images.githubusercontent.com/786968/178320561-02d79e6c-99e2-46c2-92d6-e0ca6c649dce.png)


Do you have hint to solve?

**Comment by e-Evolution** [comment]
@rjuju Thank you , I tried added the hypopg.use_real_oids = on into my postgresql.conf and is  working fine.

I wonder what is the best approach , just I saw your answer now , I will try your recommendation.

Thanks you very much, for your quick response.

**Comment by piracio** [comment]
Thanks, the software that we are using is dexter and probably is doing force brute approach.

**Comment by rjuju** [comment]
Good news!

I don't really know how dexter is working, but if it only relies on postgres planner using a hypothetical indexes to decide if such an index should be created, it seems dangerous: if there's a similar existing index, there's no guarantee that this one will be picked by postgres rather than the hypothetical index.  If anything, postgres more likely to do the opposite, as the real index will probably be bloated, and thus bigger, so more expensive than the hypothetical one (which may also be under estimated).

For pg_qualstats, I wrote some article to explain its approach: https://rjuju.github.io/postgresql/2020/01/06/pg_qualstats-2-global-index-advisor.html which also covers the caveats and limitations.

**Comment by piracio** [comment]
Thanks for all the information, I am playing with automatic index creation tools as I am workign improving the performance of Adempiere. so far is going OK, now I will deep dive into dexter and the tools that you just provide, thanks again. I will close this question.
Saludos, desde New Zealand de un Chileno.
