### ISSUE TITLE
Handling multiple hypothetical indices for the same base table

### ISSUE THREAD

**Issue by tedyu** [HypoPG/hypopg#67]
Looks like IndexOptInfo.hypothetical distinguishes hypothetical indices from real indices.

Suppose there are multiple hypothetical indices. How does hypopg let the planner know which one is more suitable for a given query ?

**Comment by rjuju** [comment]
Hi,

hypopg does no such things, as it's not its role.  This is the planner job to chose the best plan, that may or may not use an index path, to execute a query.

**Comment by luss** [comment]
AFAIK you might be looking for pg_hintplan as a compliment to HypoPG.
HypoPG can advise you on creating an index.  After the index is created, if
the planner (for some reason) doesn't want to use the index in it's default
plan, then you could add a hint to your query to "force" the planner to use
the index yopu've added.  Your mileage may vary.  There are many "purists"
in the PG Community that don't like /* Hints */.   I personally come from
an Oracle background & think they are fine to use when you think u know
better than the planner or want the stability of the plan not changing
"randomly" in the future..

**Comment by rjuju** [comment]
I totally agree that pg_hintplans can be a life saver for the few corner cases where the planner won't do the right thing (like the usual `WHERE col1 = X ORDER BY col2 LIMIT Y` that can pick an index for the ORDER BY thinking it will find matching row(s) for col1 fast enough due to the stats, while in reality that's not the case), even if I don't think it should be used lightly.

That being said, I don't think this is relevant for hypopg.  If the planner for some reason doesn't use a hypothetical index, even if you force its usage with pg_hintplans you won't be able to check whether the planner was right or not as you can't execute the query and compare the execution time.  The only way to know for sure is to create the index, thus **not** using hypopg.

**Comment by df7cb** [comment]
> I totally agree that pg_hintplans can be a life saver for the few corner cases where the planner won't do the right thing (like the usual `WHERE col1 = X ORDER BY col2 LIMIT Y` that can pick an index for the ORDER BY thinking it will find matching row(s) for col1 fast enough due to the stats, while in reality that's not the case), even if I don't think it should be used lightly.

On a sidenote, the correct fix for that "abort early" problem is an index on (col1, col2).
