### ISSUE TITLE
Compilation Error Encountered: ERROR:  could not access file "$libdir/hypopg": No such file or directory

### ISSUE THREAD

**Issue by Beliefuture** [HypoPG/hypopg#79]
Hi! When I attempt to create the extension in the psql cmd, The following error appears.
```
postgres=# create extension hypopg;
ERROR:  could not access file "$libdir/hypopg": No such file or directory
```

I have checked the file in the `$libdir` library, it does exist the file `hypopg.so`.

And the details about when running the `make install` command is below.

```
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  hypopg.so '/usr/lib64/pgsql/hypopg.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./hypopg.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./hypopg--2.0.0beta.sql ./hypopg--1.1.2.sql  '/usr/share/pgsql/extension/'
```

**Comment by rjuju** [comment]
Hi,

First of all it seems that you're trying to compile the **master** branch, which was abandoned around pg12 release as there was incompatible changes with the hypothetical partitioning. The up to date branch you should use is **REL1_STABLE**, which contains all features and bugfixes and is currently version 1.3.1 (and 1.4.0 being developed, which should be released soon).

Is there any reason why you compile it rather than installing from PGDG repositories?  As far as I know it's available for all the major distros (Debian / Ubuntu / RHEL / Rocky / Fedora...).

If you want to compile it, I'm wondering if the paths you're seeing here are for some "default" instance (without any major version indication, so should be the distro's default one), while you're using a different version (say installed from PGDG repository).  Do `pg_config --libdir` and `sudo pg_config --libdir` return the same value?  Which version of postgres are you using?  E.g. what does `SELECT version()` return?  If it's pg12 or later that's definitely not the version against which you compiled hypopg, as the master branch would only work with older versions.

**Comment by Beliefuture** [comment]
> 

Hi, thanks for your reply! The OS of the server is: CentOS. And I previously and successfully complied it from the source on other servers.

I guess it might be due to multiple postgres exist in the server, i.e., the `pg_config --libdir` and `sudo pg_config --libdir` return different value. I also notice this when I run `make install` and `sudo make install`. The path is not the same.
But I am confused about this since I have set the `dynamic_library_path` to the path when I run `sudo make install`. But it still didn't work.

As for the version, both of these postgres instances are older than 12. So it might not be the reason.

**Comment by rjuju** [comment]
> I guess it might be due to multiple postgres exist in the server, i.e., the pg_config --libdir and sudo pg_config --libdir return different value. I also notice this when I run make install and sudo make install. The path is not the same.

Ah, then in that case you're compiling for the version mentioned in `pg_config`, and installing in the version mentioned in `sudo pg_config`.  I'm assuming you're using the version from `pg_config`, as otherwise the library would be found and you would have instead an error saying that the library version is incorrect.

You could do something like:
```
sudo -E pg_config --libdir
```
and if that returns the same value then `sudo -E make install`.  Otherwise specify the pg_config location expicitly, like
```
which pg_config
sudo PG_CONFIG=/the/location/to/pg_config make install
```

**Comment by Beliefuture** [comment]
> 

Hi, thanks for your reply! Now I encountered another error, i.e.,
```
postgres=# create extension hypopg;
ERROR:  could not load library "/usr/pgsql-10/lib/hypopg.so": /usr/pgsql-10/lib/hypopg.so: undefined symbol: copyObject
```

**Comment by rjuju** [comment]
>
> Now I encountered another error, i.e.,
>
> postgres=# create extension hypopg;
> ERROR:  could not load library "/usr/pgsql-10/lib/hypopg.so": /usr/pgsql-10/lib/hypopg.so: undefined symbol: copyObject
>
>
maybe a side effect of a previous compilation. can you do a "make clean"
first, then the usual make and sudo - E make install?

also, now would be a good time to switch to branch REL1_STABLE if you
haven't yet.

**Comment by Beliefuture** [comment]
> 

Hi @rjuju, I have solved it! Thanks for your help. Another minor question is that what the main difference between the branch `hypopg-master` and `REL1_STABLE` if my pg version is older than 12? I previously adopt the `master` branch and the `1.3.1` version. Moreover, I also notice that the function `hypopg_relation_size()` might be not so accurate during my usage when the tables are small. (Maybe it is due to the inner size of these tables?)

**Comment by rjuju** [comment]
>
> Hi @rjuju <https://github.com/rjuju>, I have solved it! Thanks for your
> help.
>

good news!

> Another minor question is that what the main difference between the branch
> hypopg-master and REL1_STABLE if my pg version is older than 12? I
> previously adopt the master branch and the 1.3.1 version.
>

the master branch was abandoned 4 or 5 years ago, so you would miss that
much bug fixes and new features

> Moreover, I also notice that the function hypopg_relation_size() might be
> not so accurate during my usage when the tables are small. (Maybe it is due
> to the inner size of these tables?)
>
I think there were a few improvements on that recently (so not in the
master branch), but generally that's not surprising. the size estimation
isn't supposed to be very accurate (and it couldn't be as it depends on the
bloat on other indexes, which could be different in two otherwise identical
indexes), but of the same order of magnitude so that postgres can make an
educated decision on whether to use a hypothetical index or not. if
anything, I tried to make the size estimate pessimistic so that postgres
prefers existing indexes to hypothetical ones. but for small relations it's
likely to have a bigger error ratio in the size estimate.

>

**Comment by Beliefuture** [comment]
Hi @rjuju. I notice the following illustrations in your reply, i.e.,

> but of the same order of magnitude so that postgres can make an
educated decision on whether to use a hypothetical index or not. if
anything, I tried to make the size estimate pessimistic so that postgres
prefers existing indexes to hypothetical ones.
> […](#)

So, when considering the usage of the existing indexes and hypothetical indexes, does the optimizer of pg not just take the benefit of these indexes into account, e.g., the degree of the estimated cost reduction? I didn't look through into the source code before and accordingly was not so familiar about the inner mechanism. But it sounds interesting.

**Comment by rjuju** [comment]
Postgres wouldn't know if an index is hypothetical or not, so it would just compare them based the stats it knows and chose the one that leads to a cheapest plan.  If you create the same hypothetical as an existing one, then postgres will simply pick the one that seems the smallest, as the cost will be slightly less.  It would be the same if you create a new index that's exactly the same as an existing one: the new one will be smaller as it won't be bloated at all, and postgres is more likely to chose it.  In both case it doesn't mean that it's a good idea to create such an index.

**Comment by Beliefuture** [comment]
Hi @rjuju! Thanks for your illustration.

> If you create the same hypothetical as an existing one, then postgres will simply pick the one that seems the smallest, as the cost will be slightly less. 

For this case, it is the reason why you make the estimated size of hypothetical indexes pessimistic (larger than actually build it?). So postgres will not prefer to choose this hypothetical index but the corresponding existing ones?

> It would be the same if you create a new index that's exactly the same as an existing one: the new one will be smaller as it won't be bloated at all, and postgres is more likely to chose it.

For both the cases above, they refer to build the indexes that is totally the same, i.e., with the consistent index columns involved? If so, I have not tried to build the same/repetitive indexes under both hypothetical and existing circumstances before, but it sounds a little weird as I think this manner should be forbidden.

**Comment by rjuju** [comment]
> For this case, it is the reason why you make the estimated size of hypothetical indexes pessimistic (larger than actually build it?). So postgres will not prefer to choose this hypothetical index but the corresponding existing ones?

Partly yes, partly because it also account for things I don't estimate (like inner pages).  But as I mentioned I also didn't want to try to get a very precise size, as there wouldn't be a single size for a given index anyway.  If you put bloat in the equation you can probably get somewhere 1.5x the size, or even more, so no need to try to hard.  Getting something close enough, and not too small usually works great.

> For both the cases above, they refer to build the indexes that is totally the same, i.e., with the consistent index columns involved? If so, I have not tried to build the same/repetitive indexes under both hypothetical and existing circumstances before, but it sounds a little weird as I think this manner should be forbidden.

It's totally fine to create the same index twice (it was actually a good way to get rid of an old and very bloated index and replacing it with a fresh one before REINDEX CONCURRENTLY was added), so it shouldn't be forbidden to create a duplicated hypothetical index.  Even if it was, should the hypothetical index be automatically removed if someone else create that index?  And it can also be useful for development purpose to see if the size estimate is close enough or not.

**Comment by Beliefuture** [comment]
Hi @rjuju! Thanks for your timely reply, detailed illustration and kind help :) 
I close this issue.

**Comment by rjuju** [comment]
Thanks :)
