### ISSUE TITLE
A weird index name issue

### ISSUE THREAD

**Issue by sylph520** [HypoPG/hypopg#82]
I'm using the hypopg extension 1.1.3 for a while (installed by source code in ubuntu 20.04). A weird thing happened today, the index created by hypopg extension missed a ">" char in its name (e.g., now the name became `<1000000053btree_lineitem_l_orderkey)` from `<1000000053>btree_lineitem_l_orderkey)` ). 

it behaves normally before, and I do not recall anything that I do to trigger this abnormal behavior.  Have anyone encountered similar things, or what should I do to inspect the issues (reinstallation of the hypopg extension seems not working). 

Thanks!

**Comment by rjuju** [comment]
Hi,

That's very strange, how can you end up with an oid of more than 10B given
than oid is an unsigned int32 type? Are you using some postgres fork or
otherwise modified version?

For the record hypopg has a hard coded knowledge of the oid datatype and
uses a fixed size buffer for that, which explains why you get a truncated
name if you have an oid bigger than INT32_MAX.

**Comment by rjuju** [comment]
And I just realized that it's not 10B but 1B, and that's there's an
off-by-1 issue in the code for the fixed buffer size🤦, sorry about that.

I will push a fix as soon as I get access to my computer.

**Comment by rjuju** [comment]
I just pushed https://github.com/HypoPG/hypopg/commit/bd45b0219ed2d46ebce8e1385f96951ed82cfce5 which should fix the issue.

**Comment by sylph520** [comment]
> I just pushed [bd45b02](https://github.com/HypoPG/hypopg/commit/bd45b0219ed2d46ebce8e1385f96951ed82cfce5) which should fix the issue.

Thanks for the quick fix, it work normally now.😊

**Comment by rjuju** [comment]
Thanks for the feedback!
