### ISSUE TITLE
We couldn't get plans for this query, presumably because some parameters are missing: syntax error at or near "then"

### ISSUE THREAD

**Issue by saidterzi** [HypoPG/hypopg#93]
Hello,

Firstly, thanks for this awesome project.

I am having an issue with an sql query, which results the error message i wrote to the title.

`select inlandvoya0_.id as col_0_0_, case when inlandvoya0_.load_district_id=$6 then $7 when inlandvoya0_.arrival_district_id=$8 then $9 when inlandvoya0_.status_id=$10 then $11 when inlandvoya0_.status_id=$12 then $13 when inlandvoya0_.status_id=$14 then $15 when inlandvoya0_.status_id=$16 then $17 end as col_1_0_, array_to_string(array((select distinct coalesce((select translatio2_.value from translation_value translatio2_...REDACTED`

What is the problem, do you have any idea?

**Comment by rjuju** [comment]
Hello,

thanks a lot!

I think that the error message is coming from powa-web right? This is because the query text comes from pg_stat_statements, which normalise it and remove all constant values. It then relies on pg_qualstats to get the predicates values, but the constant values in the select part are not predicates and therefore not saved by pg_qualstats. So when powa-web tries to recreate a query to test hypothetical indexes it gets a syntax error.

I think that postgres now supports EXPLAIN with the query provided by pg_stat_statements as is, so maybe powa could try it too as a fallback.

**Comment by Thigoe** [comment]
Thank you for your quick response! I will inform them.
